# Generated by Django 5.0.3 on 2024-10-04 07:36

import sortedm2m.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_room_messages_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='messages',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='chat.message', verbose_name='Сообщения'),
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('user_chat', 'user_chat'), ('group_chat', 'group_chat')], default='user_chat', max_length=30),
        ),
    ]
