# Generated by Django 5.0.3 on 2024-10-16 09:50

import django.db.models.deletion
import sortedm2m.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_room_room_messages_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.room', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
