# Generated by Django 5.0.3 on 2024-10-16 09:55

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_room_messages_message_room_alter_room_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='messages',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='chat.message', verbose_name='Сообщения'),
        ),
    ]
